name: Build and Run Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    CONFIG: Release
    XUNIT3_PROJECT: Sauceless/Sauceless.csproj
    COVERAGE_FORMAT: cobertura
    XUNIT3_INTEGRATION_COVERAGE_FILENAME: cobertura.xunit3.integration.xml

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c ${{ env.CONFIG }}

      - name: Run integration tests
        run: dotnet test --no-build -c ${{ env.CONFIG }} --logger trx